In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
import pandas as pd

df = pd.read_csv("../data/traffic_dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
df = pd.read_csv(r"D:\Traffice-System\data\traffic_dataset.csv")

In [6]:
df.head()

,filename,date,timestamp,direction,day_night,weather,start_frame,number_of_frames,traffic_class,notes
0,cctv052x2004080516x01638,20040805,16.01638,south,day,overcast,2,53,medium,NaN
1,cctv052x2004080516x01639,20040805,16.01639,south,day,overcast,2,53,medium,NaN
2,cctv052x2004080516x01640,20040805,16.01640,south,day,overcast,2,48,light,NaN
3,cctv052x2004080516x01641,20040805,16.01641,south,day,overcast,2,52,medium,NaN
4,cctv052x2004080516x01642,20040805,16.01642,south,day,overcast,2,51,medium,NaN

In [7]:
df.tail()

,filename,date,timestamp,direction,day_night,weather,start_frame,number_of_frames,traffic_class,notes
249,cctv052x2004080619x00104,20040806,19.00104,south,day,clear,2,53,light,NaN
250,cctv052x2004080620x00105,20040806,20.00105,south,day,clear,2,52,light,NaN
251,cctv052x2004080620x00106,20040806,20.00106,south,day,clear,2,53,light,NaN
252,cctv052x2004080620x00107,20040806,20.00107,south,day,clear,2,53,light,NaN
253,cctv052x2004080620x00108,20040806,20.00108,south,day,clear,2,52,light,NaN

In [8]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 254
Number of columns: 10

In [9]:
print("Column names:")

for column in df.columns:
    print(column)

Column names:
filename
date
timestamp
direction
day_night
weather
start_frame
number_of_frames
traffic_class
notes

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   filename          254 non-null    str
 1   date              254 non-null    int64
 2   timestamp         254 non-null    float64
 3   direction         254 non-null    str
 4   day_night         254 non-null    str
 5   weather           254 non-null    str
 6   start_frame       254 non-null    int64
 7   number_of_frames  254 non-null    int64
 8   traffic_class     254 non-null    str
 9   notes             14 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 20.0 KB

In [11]:
df.describe()

               date   timestamp  start_frame  number_of_frames
count  2.540000e+02  254.000000        254.0        254.000000
mean   2.004081e+07   13.841694          2.0         52.429134
std    4.280224e-01    4.278468          0.0          1.297953
min    2.004080e+07    6.018200          2.0         43.000000
25%    2.004081e+07   10.018853          2.0         52.000000
50%    2.004081e+07   15.000355          2.0         53.000000
75%    2.004081e+07   17.016627          2.0         53.000000
max    2.004081e+07   20.017000          2.0         53.000000

In [12]:
df.describe(include="all")

,filename,date,timestamp,direction,day_night,weather,start_frame,number_of_frames,traffic_class,notes
count,254,2.540000e+02,254.000000,254,254,254,254.0,254.000000,254,14
unique,254,NaN,NaN,1,1,3,NaN,NaN,3,2
top,cctv052x2004080516x01638,NaN,NaN,south,day,overcast,NaN,NaN,light,drops on lens
freq,1,NaN,NaN,254,254,125,NaN,NaN,165,13
mean,NaN,2.004081e+07,13.841694,NaN,NaN,NaN,2.0,52.429134,NaN,NaN
std,NaN,4.280224e-01,4.278468,NaN,NaN,NaN,0.0,1.297953,NaN,NaN
min,NaN,2.004080e+07,6.018200,NaN,NaN,NaN,2.0,43.000000,NaN,NaN
25%,NaN,2.004081e+07,10.018853,NaN,NaN,NaN,2.0,52.000000,NaN,NaN
50%,NaN,2.004081e+07,15.000355,NaN,NaN,NaN,2.0,53.000000,NaN,NaN
75%,NaN,2.004081e+07,17.016627,NaN,NaN,NaN,2.0,53.000000,NaN,NaN
max,NaN,2.004081e+07,20.017000,NaN,NaN,NaN,2.0,53.000000,NaN,NaN

In [13]:
print("Missing values in each column:")

print(df.isnull().sum())

Missing values in each column:
filename              0
date                  0
timestamp             0
direction             0
day_night             0
weather               0
start_frame           0
number_of_frames      0
traffic_class         0
notes               240
dtype: int64

In [14]:
missing_percentage = (
    df.isnull().sum() / len(df) * 100
)

print(missing_percentage)

filename             0.000000
date                 0.000000
timestamp            0.000000
direction            0.000000
day_night            0.000000
weather              0.000000
start_frame          0.000000
number_of_frames     0.000000
traffic_class        0.000000
notes               94.488189
dtype: float64

In [15]:
print("Number of duplicate rows:")

print(df.duplicated().sum())

Number of duplicate rows:
0

In [16]:
for column in df.columns:
    print("\n", column)
    print(df[column].unique())

 filename
<StringArray>
['cctv052x2004080516x01638', 'cctv052x2004080516x01639',
 'cctv052x2004080516x01640', 'cctv052x2004080516x01641',
 'cctv052x2004080516x01642', 'cctv052x2004080516x01643',
 'cctv052x2004080516x01644', 'cctv052x2004080516x01645',
 'cctv052x2004080516x01646', 'cctv052x2004080516x01647',
 ...
 'cctv052x2004080619x00099', 'cctv052x2004080619x00100',
 'cctv052x2004080619x00101', 'cctv052x2004080619x00102',
 'cctv052x2004080619x00103', 'cctv052x2004080619x00104',
 'cctv052x2004080620x00105', 'cctv052x2004080620x00106',
 'cctv052x2004080620x00107', 'cctv052x2004080620x00108']
Length: 254, dtype: str

 date
[20040805 20040806]

 timestamp
[16.01638 16.01639 16.0164  16.01641 16.01642 16.01643 16.01644 16.01645
 16.01646 16.01647 16.01648 16.01649 16.0165  17.01652 17.01653 17.01654
 17.01655 17.01656 17.01657 17.01658 17.01659 17.0166  17.01661 17.01662
 17.01663 17.01664 17.01665 18.01666 18.01667 18.01668 18.01669 18.0167
 18.01671 18.01672 18.01673 18.01674 18.01675 18.01676 18.01677 19.01678
 19.01679 19.0168  19.01681 19.01682 19.01683 19.01684 19.01685 19.01686
 19.01687 19.01688 19.01689 19.0169  19.01691 19.01692 19.01693 20.01694
 20.01695 20.01697 20.01698 20.01699 20.017    6.0182   6.01821  6.01822
  6.01823  6.01824  6.01826  6.01827  6.01828  6.01829  6.0183   6.01831
  6.01832  6.01833  6.01834  7.01835  7.01836  7.01837  7.01838  7.01839
  7.0184   7.01841  7.01842  7.01843  7.01844  7.01845  7.01846  7.01847
  7.01848  8.01849  8.0185   8.01851  8.01852  8.01853  8.01854  8.01855
  8.01856  8.01857  8.01858  9.01859  9.0186   9.01861  9.01862  9.01863
  9.01864  9.01865  9.01866  9.01867  9.01869  9.0187   9.01871  9.01872
  9.01873  9.01874  9.01875  9.01876 10.01877 10.01878 10.01879 10.0188
 10.01881 10.01882 10.01883 10.01884 10.01885 10.01886 10.01887 10.01889
 10.0189  10.01891 10.01892 11.01894 11.01895 11.01896 11.01897 11.01898
 11.01899 11.019   11.01901 11.01902 11.01903 11.01904 11.01905 11.01906
 11.01907 12.      12.00002 12.00003 12.00004 12.00005 12.00006 12.00007
 12.01908 12.01909 12.0191  12.01911 12.01912 12.01913 12.01914 12.01915
 13.00008 13.00009 13.0001  13.00011 13.00012 13.00013 13.00014 13.00015
 13.00016 13.00017 13.00018 14.00019 14.0002  14.00021 14.00022 14.00023
 14.00024 14.00025 14.00026 14.00027 15.00028 15.00029 15.0003  15.00031
 15.00032 15.00033 15.00034 15.00035 15.00036 15.00037 15.00038 15.00039
 15.0004  15.00041 15.00044 15.00045 16.00046 16.00047 16.00048 16.00049
 16.0005  16.00051 16.00052 16.00053 16.00054 16.00055 16.00056 16.00057
 16.00058 16.00059 16.0006  16.00061 16.00062 17.00064 17.00065 17.00066
 17.00067 17.00068 17.00069 17.0007  17.00071 17.00072 17.00073 17.00074
 17.00075 17.00076 17.00077 18.00079 18.0008  18.00081 18.00085 18.00086
 18.00087 18.00088 18.00089 19.0009  19.00091 19.00092 19.00093 19.00094
 19.00095 19.00096 19.00097 19.00098 19.00099 19.001   19.00101 19.00102
 19.00103 19.00104 20.00105 20.00106 20.00107 20.00108]

 direction
<StringArray>
['south']
Length: 1, dtype: str

 day_night
<StringArray>
['day']
Length: 1, dtype: str

 weather
<StringArray>
['overcast', 'clear', 'rain']
Length: 3, dtype: str

 start_frame
[2]

 number_of_frames
[53 48 52 51 49 47 50 44 43]

 traffic_class
<StringArray>
['medium', 'light', 'heavy']
Length: 3, dtype: str

 notes
<StringArray>
[nan, 'drops on lens', 'ambiguous']
Length: 3, dtype: str

In [17]:
print(df.nunique())

filename            254
date                  2
timestamp           254
direction             1
day_night             1
weather               3
start_frame           1
number_of_frames      9
traffic_class         3
notes                 2
dtype: int64

In [18]:
print(df["traffic_class"].value_counts())

traffic_class
light     165
medium     45
heavy      44
Name: count, dtype: int64

In [19]:
class_percentage = (
    df["traffic_class"]
    .value_counts(normalize=True) * 100
)

print(class_percentage.round(2))

traffic_class
light     64.96
medium    17.72
heavy     17.32
Name: proportion, dtype: float64

In [20]:
print(df["weather"].value_counts())

weather
overcast    125
rain         78
clear        51
Name: count, dtype: int64

In [21]:
print(df["day_night"].value_counts())

day_night
day    254
Name: count, dtype: int64

In [22]:
print(df["direction"].value_counts())

direction
south    254
Name: count, dtype: int64

## Final observation
The dataset contains 254 traffic samples with 10 columns.
The target variable is traffic_class.
The traffic classes are Light, Medium, and Heavy.
The dataset contains information such as weather, direction, day/night, date, and frames.
The dataset was successfully loaded and its basic structure was explored.